# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
